package auth

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"

	"golang.org/x/oauth2"
)

func TestAuthorizeUsesDynamicLoopbackPKCEAndExactRedirect(t *testing.T) {
	var tokenRequest url.Values
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseForm(); err != nil {
			t.Fatal(err)
		}
		tokenRequest = r.Form
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"access_token":"access-secret","token_type":"Bearer","refresh_token":"refresh-secret","expires_in":3600,"scope":"user-read-private user-library-read user-library-modify"}`))
	}))
	defer server.Close()

	var authURL *url.URL
	authorizer := Authorizer{
		HTTPClient: server.Client(),
		Endpoints:  Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL},
		Timeout:    2 * time.Second,
		OpenBrowser: func(raw string) error {
			var err error
			authURL, err = url.Parse(raw)
			if err != nil {
				return err
			}
			callback := authURL.Query().Get("redirect_uri") + "?code=auth-code&state=" + url.QueryEscape(authURL.Query().Get("state"))
			go func() {
				response, getErr := http.Get(callback) // #nosec G107 -- test callback URL is generated by the local authorizer.
				if getErr == nil {
					_ = response.Body.Close()
				}
			}()
			return nil
		},
	}
	var stderr bytes.Buffer
	got, err := authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "http://127.0.0.1/callback", ErrOut: &stderr,
	})
	if err != nil {
		t.Fatal(err)
	}
	if got.AccessToken != "access-secret" || got.RefreshToken != "refresh-secret" {
		t.Fatalf("token = %+v", got)
	}
	if want := []string{ScopeUserLibraryModify, ScopeUserLibraryRead, ScopeUserReadPrivate}; !slices.Equal(got.Scopes, want) {
		t.Fatalf("scopes = %v, want %v", got.Scopes, want)
	}
	if authURL == nil || authURL.Query().Get("code_challenge_method") != "S256" ||
		authURL.Query().Get("scope") != "user-library-modify user-library-read user-read-private" {
		t.Fatalf("authorization URL = %v", authURL)
	}
	redirect := authURL.Query().Get("redirect_uri")
	if !strings.HasPrefix(redirect, "http://127.0.0.1:") || !strings.HasSuffix(redirect, "/callback") {
		t.Fatalf("dynamic redirect = %q", redirect)
	}
	if tokenRequest.Get("redirect_uri") != redirect || tokenRequest.Get("client_id") != "client-id" || tokenRequest.Get("code") != "auth-code" {
		t.Fatalf("token request = %v", tokenRequest)
	}
	if oauth2.S256ChallengeFromVerifier(tokenRequest.Get("code_verifier")) != authURL.Query().Get("code_challenge") {
		t.Fatal("token exchange verifier does not match authorization challenge")
	}
	if !strings.Contains(stderr.String(), authURL.String()) {
		t.Fatalf("stderr did not contain authorization URL: %q", stderr.String())
	}
}

func TestOAuthConfigOwnsItsExactScopes(t *testing.T) {
	authorizer := Authorizer{}
	first := authorizer.oauthConfig("client-id", "http://127.0.0.1/callback")
	first.Scopes[0] = "mutated"

	second := authorizer.oauthConfig("client-id", "http://127.0.0.1/callback")
	want := []string{ScopeUserLibraryModify, ScopeUserLibraryRead, ScopeUserReadPrivate}
	if !slices.Equal(second.Scopes, want) {
		t.Fatalf("scopes = %v, want %v", second.Scopes, want)
	}
}

func TestAuthorizeAcceptsUppercaseSchemeAndRootLoopbackPath(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
		writer.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(writer, `{"access_token":"access","token_type":"Bearer","refresh_token":"refresh","expires_in":3600,"scope":"user-read-private"}`)
	}))
	defer server.Close()
	authorizer := Authorizer{
		HTTPClient: server.Client(),
		Endpoints:  Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL},
		Timeout:    2 * time.Second,
		OpenBrowser: func(raw string) error {
			authURL, err := url.Parse(raw)
			if err != nil {
				return err
			}
			callback, err := url.Parse(authURL.Query().Get("redirect_uri"))
			if err != nil {
				return err
			}
			callback.Scheme = strings.ToLower(callback.Scheme)
			callback.Path = "/"
			query := callback.Query()
			query.Set("code", "code")
			query.Set("state", authURL.Query().Get("state"))
			callback.RawQuery = query.Encode()
			go func() {
				response, getErr := http.Get(callback.String()) // #nosec G107 -- test callback URL is generated by the local authorizer.
				if getErr == nil {
					_ = response.Body.Close()
				}
			}()
			return nil
		},
	}
	if _, err := authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "HTTP://127.0.0.1", ErrOut: io.Discard,
	}); err != nil {
		t.Fatal(err)
	}
}

func TestAuthorizeRejectsWrongStateWithoutExchangeOrLeak(t *testing.T) {
	var expectedState string
	authorizer := Authorizer{
		Endpoints: Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: "https://accounts.example/token"},
		Timeout:   2 * time.Second,
		OpenBrowser: func(raw string) error {
			authURL, err := url.Parse(raw)
			if err != nil {
				return err
			}
			expectedState = authURL.Query().Get("state")
			callback := authURL.Query().Get("redirect_uri") + "?code=auth-code&state=wrong-state-sentinel"
			go func() {
				response, getErr := http.Get(callback) // #nosec G107 -- test callback URL is generated by the local authorizer.
				if getErr == nil {
					_ = response.Body.Close()
				}
			}()
			return nil
		},
	}
	_, err := authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "http://127.0.0.1/callback", ErrOut: io.Discard,
	})
	if !errors.Is(err, ErrStateMismatch) {
		t.Fatalf("error = %v, want ErrStateMismatch", err)
	}
	if strings.Contains(err.Error(), expectedState) || strings.Contains(err.Error(), "wrong-state-sentinel") {
		t.Fatalf("state leaked in error: %v", err)
	}
}

func TestAuthorizeReadsCompleteRedirectURLFromStdinWithoutBrowser(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"access_token":"access","token_type":"Bearer","refresh_token":"refresh","expires_in":3600,"scope":"user-read-private"}`))
	}))
	defer server.Close()

	reader, writer := io.Pipe()
	urls := make(chan string, 1)
	authorizer := Authorizer{
		HTTPClient: server.Client(),
		Endpoints:  Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL},
		OpenBrowser: func(string) error {
			t.Fatal("--auth-code-stdin opened a browser")
			return nil
		},
	}
	result := make(chan error, 1)
	go func() {
		_, err := authorizer.Authorize(context.Background(), Request{
			ClientID: "client-id", RedirectURI: "https://callback.example/spotify", AuthCodeStdin: true,
			In: reader, ErrOut: &authURLWriter{urls: urls},
		})
		result <- err
	}()

	raw := <-urls
	authURL, err := url.Parse(raw)
	if err != nil {
		t.Fatal(err)
	}
	callback := authURL.Query().Get("redirect_uri") + "?code=auth-code&state=" + url.QueryEscape(authURL.Query().Get("state"))
	_, _ = io.WriteString(writer, callback+"\n")
	_ = writer.Close()
	if err := <-result; err != nil {
		t.Fatal(err)
	}
}

func TestAuthorizeStdinTreatsEmptyAndSlashRootPathsEqually(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
		writer.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(writer, `{"access_token":"access","token_type":"Bearer","refresh_token":"refresh","expires_in":3600,"scope":"user-read-private"}`)
	}))
	defer server.Close()
	reader, writer := io.Pipe()
	urls := make(chan string, 1)
	result := make(chan error, 1)
	authorizer := Authorizer{
		HTTPClient: server.Client(),
		Endpoints:  Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL},
	}
	go func() {
		_, err := authorizer.Authorize(context.Background(), Request{
			ClientID: "client-id", RedirectURI: "https://callback.example", AuthCodeStdin: true,
			In: reader, ErrOut: &authURLWriter{urls: urls},
		})
		result <- err
	}()
	authURL, err := url.Parse(<-urls)
	if err != nil {
		t.Fatal(err)
	}
	callback := authURL.Query().Get("redirect_uri") + "/?code=code&state=" + url.QueryEscape(authURL.Query().Get("state"))
	_, _ = io.WriteString(writer, callback)
	_ = writer.Close()
	if err := <-result; err != nil {
		t.Fatal(err)
	}
}

func TestAuthorizeRejectsRawCodeAndTimesOutWithoutBrowser(t *testing.T) {
	authorizer := Authorizer{
		Endpoints: Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: "https://accounts.example/token"},
		Timeout:   10 * time.Millisecond,
		OpenBrowser: func(string) error {
			t.Fatal("--no-browser opened a browser")
			return nil
		},
	}
	_, err := authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "https://callback.example/spotify", AuthCodeStdin: true,
		In: strings.NewReader("raw-authorization-code\n"), ErrOut: io.Discard,
	})
	if !errors.Is(err, ErrInvalidCallback) {
		t.Fatalf("raw code error = %v, want ErrInvalidCallback", err)
	}

	_, err = authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "http://127.0.0.1/callback", NoBrowser: true, ErrOut: io.Discard,
	})
	if !errors.Is(err, ErrAuthorizationTimeout) {
		t.Fatalf("timeout error = %v, want ErrAuthorizationTimeout", err)
	}
}

func TestAuthorizeReportsDenialWithoutLeakingCallbackValues(t *testing.T) {
	const denialSentinel = "denial-value-sentinel"
	responses := make(chan string, 1)
	authorizer := Authorizer{
		Endpoints: Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: "https://accounts.example/token"},
		Timeout:   2 * time.Second,
		OpenBrowser: func(raw string) error {
			authURL, err := url.Parse(raw)
			if err != nil {
				return err
			}
			callback := authURL.Query().Get("redirect_uri") + "?error=" + denialSentinel + "&state=" + url.QueryEscape(authURL.Query().Get("state"))
			go func() {
				response, getErr := http.Get(callback) // #nosec G107 -- test callback URL is generated by the local authorizer.
				if getErr != nil {
					responses <- getErr.Error()
					return
				}
				defer func() { _ = response.Body.Close() }()
				body, _ := io.ReadAll(response.Body)
				responses <- string(body)
			}()
			return nil
		},
	}
	_, err := authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "http://127.0.0.1/callback", ErrOut: io.Discard,
	})
	if !errors.Is(err, ErrAccessDenied) {
		t.Fatalf("error = %v, want ErrAccessDenied", err)
	}
	if strings.Contains(err.Error(), denialSentinel) || strings.Contains(<-responses, denialSentinel) {
		t.Fatal("authorization denial leaked callback value")
	}
}

func TestAuthorizeContinuesAfterBrowserOpenFailure(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, `{"access_token":"access","token_type":"Bearer","refresh_token":"refresh","expires_in":3600,"scope":"user-read-private"}`)
	}))
	defer server.Close()

	authorizer := Authorizer{
		HTTPClient: server.Client(),
		Endpoints:  Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL},
		Timeout:    2 * time.Second,
		OpenBrowser: func(raw string) error {
			authURL, err := url.Parse(raw)
			if err != nil {
				return err
			}
			callback := authURL.Query().Get("redirect_uri") + "?code=code&state=" + url.QueryEscape(authURL.Query().Get("state"))
			go func() {
				response, getErr := http.Get(callback) // #nosec G107 -- test callback URL is generated by the local authorizer.
				if getErr == nil {
					_ = response.Body.Close()
				}
			}()
			return errors.New("browser-launch-detail-sentinel")
		},
	}
	var stderr bytes.Buffer
	if _, err := authorizer.Authorize(context.Background(), Request{
		ClientID: "client-id", RedirectURI: "http://127.0.0.1/callback", ErrOut: &stderr,
	}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stderr.String(), "Could not open browser automatically") || strings.Contains(stderr.String(), "browser-launch-detail-sentinel") {
		t.Fatalf("stderr = %q", stderr.String())
	}
}

func TestAuthorizeExchangeFailureDoesNotLeakCodeOrVerifier(t *testing.T) {
	const code = "authorization-code-sentinel"
	var verifier string
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if err := request.ParseForm(); err != nil {
			t.Error(err)
		}
		verifier = request.Form.Get("code_verifier")
		writer.Header().Set("Content-Type", "application/json")
		writer.WriteHeader(http.StatusBadRequest)
		_, _ = fmt.Fprintf(writer, `{"error":"invalid_grant","error_description":"echo %s %s"}`, code, verifier)
	}))
	defer server.Close()

	reader, writer := io.Pipe()
	urls := make(chan string, 1)
	var stderr bytes.Buffer
	result := make(chan error, 1)
	authorizer := Authorizer{
		HTTPClient: server.Client(),
		Endpoints:  Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL},
	}
	go func() {
		_, err := authorizer.Authorize(context.Background(), Request{
			ClientID: "client-id", RedirectURI: "https://callback.example/spotify", AuthCodeStdin: true,
			In: reader, ErrOut: io.MultiWriter(&stderr, &authURLWriter{urls: urls}),
		})
		result <- err
	}()
	authURL, err := url.Parse(<-urls)
	if err != nil {
		t.Fatal(err)
	}
	callback := authURL.Query().Get("redirect_uri") + "?code=" + code + "&state=" + url.QueryEscape(authURL.Query().Get("state"))
	_, _ = io.WriteString(writer, callback)
	_ = writer.Close()
	err = <-result
	if !errors.Is(err, ErrExchange) {
		t.Fatalf("error = %v, want ErrExchange", err)
	}
	combined := stderr.String() + err.Error()
	if verifier == "" || strings.Contains(combined, code) || strings.Contains(combined, verifier) {
		t.Fatalf("exchange secret leaked: %q", combined)
	}
}

func TestAuthorizeDistinguishesOmittedAndEmptyScope(t *testing.T) {
	for _, test := range []struct {
		name    string
		scope   string
		wantErr error
	}{
		{name: "omitted scope"},
		{name: "empty scope", scope: `,"scope":""`, wantErr: ErrExchange},
	} {
		t.Run(test.name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
				writer.Header().Set("Content-Type", "application/json")
				_, _ = fmt.Fprintf(writer, `{"access_token":"access","token_type":"Bearer","refresh_token":"refresh","expires_in":3600%s}`, test.scope)
			}))
			defer server.Close()
			reader, writer := io.Pipe()
			urls := make(chan string, 1)
			result := make(chan error, 1)
			authorizer := Authorizer{HTTPClient: server.Client(), Endpoints: Endpoints{
				AuthorizeURL: "https://accounts.example/authorize", TokenURL: server.URL,
			}}
			go func() {
				_, err := authorizer.Authorize(context.Background(), Request{
					ClientID: "client-id", RedirectURI: "https://callback.example/spotify", AuthCodeStdin: true,
					In: reader, ErrOut: &authURLWriter{urls: urls},
				})
				result <- err
			}()
			authURL, err := url.Parse(<-urls)
			if err != nil {
				t.Fatal(err)
			}
			callback := authURL.Query().Get("redirect_uri") + "?code=code&state=" + url.QueryEscape(authURL.Query().Get("state"))
			_, _ = io.WriteString(writer, callback)
			_ = writer.Close()
			err = <-result
			if !errors.Is(err, test.wantErr) {
				t.Fatalf("error = %v, want %v", err, test.wantErr)
			}
		})
	}
}

func TestAuthorizeCancellationClosesListener(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	var address string
	authorizer := Authorizer{
		Endpoints: Endpoints{AuthorizeURL: "https://accounts.example/authorize", TokenURL: "https://accounts.example/token"},
		OpenBrowser: func(raw string) error {
			authURL, err := url.Parse(raw)
			if err != nil {
				return err
			}
			redirect, err := url.Parse(authURL.Query().Get("redirect_uri"))
			if err != nil {
				return err
			}
			address = redirect.Host
			cancel()
			return nil
		},
	}
	started := time.Now()
	_, err := authorizer.Authorize(ctx, Request{
		ClientID: "client-id", RedirectURI: "http://127.0.0.1/callback", ErrOut: io.Discard,
	})
	if !errors.Is(err, context.Canceled) || time.Since(started) > time.Second {
		t.Fatalf("error = %v after %s", err, time.Since(started))
	}
	listener, err := net.Listen("tcp4", address) // #nosec G102 -- verifies that the test loopback listener was closed.
	if err != nil {
		t.Fatalf("callback listener remained open: %v", err)
	}
	_ = listener.Close()
}

type authURLWriter struct {
	mu   sync.Mutex
	urls chan<- string
}

func (writer *authURLWriter) Write(data []byte) (int, error) {
	writer.mu.Lock()
	defer writer.mu.Unlock()
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(strings.TrimPrefix(line, "Authorization URL:"))
		if strings.HasPrefix(line, "https://accounts.example/authorize") {
			select {
			case writer.urls <- line:
			default:
			}
		}
	}
	return len(data), nil
}
